alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias nv='nvim'
alias vim='nvim'
alias snv='sudo nvim'
alias py='python'
alias cat='bat --theme TwoDark'
alias cd='z'
alias preview='fzf --preview="bat --color=always {}"'
alias root='sudo -i'
alias shutdown='shutdown -h now'
alias system='sudo systemctl'
alias process='ps aux | grep'
alias config='cd ~/Dotfiles/.config/; nv'
alias hist='history'

alias ls='lsd --color=auto --group-directories-first'
alias la='ls -a'
alias ll='ls -l'
alias lcf='ls -CF'
alias lt='ls --tree'
alias find='find . | grep '

alias home='cd'
alias docs='cd ~/Documents'
alias downloads='cd ~/Downloads'
alias web='cd /var/www/html'
alias ..='cd ..'
alias dots='cd ~/Dotfiles/'
