#  _____            _                                      _
# | ____|_ ____   _(_)_ __ ___  _ __  _ __ ___   ___ _ __ | |_
# |  _| | '_ \ \ / / | '__/ _ \| '_ \| '_ ` _ \ / _ \ '_ \| __|
# | |___| | | \ V /| | | | (_) | | | | | | | | |  __/ | | | |_
# |_____|_| |_|\_/ |_|_|  \___/|_| |_|_| |_| |_|\___|_| |_|\__|
#
# https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE, 24
env = XCURSOR_THEME, Bibata-Modern-Classic 
env = HYPRCURSOR_SIZE, 24
env = HYPRCURSOR_THEME, Bibata-Modern-Classic

env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

env = XDG_CURRENT_DESKTOP,Hyprland 
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland


