#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

color_prompt=yes

# Filesystem-related commands
alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -l'
alias lcf='ls -CF'
alias find='find . | grep '

# Directory-related commands
alias home='cd'
alias docs='cd ~/Documents'
alias downloads='cd ~/Downloads'
alias ..='cd ..'

# Pacman-related commands
alias install='sudo pacman -S'
alias remove='sudo pacman -Rns'
alias update='sudo pacman -Syu'
alias packages='pacman -Qem'
alias cleancache='sudo pacman -Sc'

# Yay-related commands
alias aur-install='yay -S'
alias aur-remove='yay -Rns'
alias aur-update='yay -Syu'
alias aur-packages='yay -Qem'
alias aur-cleancache='yay -Sc'

# Utilities
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias nv='nvim'
alias vim='nvim'
alias snv='sudo nvim'
alias py='python'
alias gpt='chatgpt-cli'

# System-related commands
alias root='sudo -i'
alias shutdown='shutdown -h now'
alias system='sudo systemctl'
alias process='ps aux | grep'

# Extracting files
extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xvjf $1    ;;
            *.tar.gz)    tar xvzf $1    ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       rar x $1       ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xvf $1     ;;
            *.tbz2)      tar xvjf $1    ;;
            *.tgz)       tar xvzf $1    ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)           echo "I don't know how to extract '$1'" ;;
        esac
    else
        echo "'$1' is not a valid file!"
    fi
}

# Shell control
eval "$(thefuck --alias)"

# Welcome Neofetch
echo ""
fastfetch -c ~/.config/fastfetch/config.jsonc
echo ""

# PS1 Variable for user inputs
PS1='\[\033[01;37m\](\[\033[01;30m\]\u\033[01;37m\]@\033[01;36m\]\h\[\033[01;37m\])\[\033[00;37m\] on \[\033[01;32m\]\t\[\033[01;37m\] [\W]\033[00;37m\]\n 󰁕 '

unset color_prompt force_color_prompt

. "$HOME/.cargo/env"

export JAVA_HOME='/usr/lib/jvm/java-22-openjdk'
export PATH=$JAVA_HOME/bin:$PATH


export PATH=$PATH:$ANDROID_HOME/platform-tools

export HADOOP_HOME=/home/Shisones/Hadoop
export PATH=$PATH:$HADOOP_HOME/bin
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop


export SPARK_HOME='/home/Shisones/Spark'
export PATH=$PATH:$SPARK_HOME/bin
export SPARK_DIST_CLASSPATH=$(~/Hadoop/bin/hadoop classpath)
export LD_LIBRARY_PATH=$HADOOP_HOME/lib/native 

export OPENAI_API_KEY='gaboleh tau wkokwokw'
export ANDROID_SDK_ROOT='/opt/android-sdk'
export ANDROID_HOME='/home/Shisones/android-sdk'

