[window]
    decorations= "Full"
    opacity = 0.95
    blur = false 
    dynamic_padding = true

    [window.padding]
        x = 5
        y = 5 

[cursor]
    [cursor.style]
        shape = "Underline"
        blinking = "On"

[terminal]
   shell = "zsh"

[colors]
    [colors.primary]
        background = "#2E3440"
        foreground = "#E5E9F0"

    [colors.normal]
        black = "#4C566A"
        red = "#BF616A"
        green = "#A3BE8C"
        yellow = "#EBCB8B"
        blue = "#81A1C1"
        magenta = "#B988B0"
        cyan = "#88C0D0"
        white = "#E5E9F0"

    [colors.bright]
        black = "#4C566A"
        red = "#BF616A"
        green = "#A3BE8C"
        yellow = "#EBCB8B"
        blue = "#81A1C1"
        magenta = "#B988B0"
        cyan = "#8FBCBB"
        white = "#ECEFF4"

    [colors.search]
    [colors.search.matches]
        foreground = "#81A1C1"
        background = "#4C566A"

    [colors.search.focused_match]
        foreground = "#EBCB8B"
        background = "#4C566A"

    [colors.hints]
    [colors.hints.start]
        foreground = "#B988B0"
        background = "#4C566A"

    [colors.hints.end]
        foreground = "#81A1C1"
        background = "#4C566A"

    [colors.selection]
        text = "CellForeground"
        background = "#3F4758"

    [font]
        size = 10


    [font.normal]
        family = "SauceCodePro Nerd Font"
        style = "Bold"
