#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

color_prompt=yes

# GNU Utils-related commands
alias ls='lsd --color=auto --group-directories-first'
alias la='ls -a'
alias ll='ls -l'
alias lcf='ls -CF'
alias find='find . | grep '
alias hist='history'

# Directory-related commands
alias home='cd'
alias docs='cd ~/Documents'
alias downloads='cd ~/Downloads'
alias web='cd /var/www/html'
alias ..='cd ..'

# Pacman-related commands
alias install='sudo pacman -S'
alias uninstall='sudo pacman -Rns'
alias update='sudo pacman -Syu'
alias packages='pacman -Qen'
alias cleancache='sudo pacman -Sc'

# Paru-related commands
alias aur-install='paru -S'
alias aur-uninstall='paru -Rns'
alias aur-update='paru -Syu'
alias aur-packages='paru -Qem'
alias aur-cleancache='paru -Sc'

# Utilities
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias nv='nvim'
alias vim='nvim'
alias snv='sudo nvim'
alias py='python'
alias gpt='chatgpt-cli'
alias cat='bat --theme TwoDark'
alias cd='z'
alias preview='fzf --preview="bat --color=always {}"'
alias mongo='mongosh'

# System-related commands
alias root='sudo -i'
alias shutdown='shutdown -h now'
alias system='sudo systemctl'
alias process='ps aux | grep'
alias dinamik='ssh dinamik@cpdinamik.kemakom.org -i ~/.ssh/shisones_id -p 64646'

# Functions
extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xvjf $1    ;;
            *.tar.gz)    tar xvzf $1    ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       rar x $1       ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xvf $1     ;;
            *.tbz2)      tar xvjf $1    ;;
            *.tgz)       tar xvzf $1    ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)           echo "I don't know how to extract '$1'" ;;
        esac
    else
        echo "'$1' is not a valid file!"
    fi
}


# Shell control
eval "$(thefuck --alias)"
eval "$(zoxide init bash)"

. "$HOME/.cargo/env"

# Welcome Neofetch
echo ""
fastfetch -c ~/.config/fastfetch/config.jsonc
echo ""

# PS1 Variable for user inputs
PS1='\[\033[01;37m\][\[\033[01;30m\]\u\033[01;37m\]@\033[01;36m\]\h\[\033[01;37m\]]\[\033[00;37m\] on \[\033[01;32m\]\t\[\033[01;37m\] [\W]\033[00;37m\]\n 󰁕 '
unset color_prompt force_color_prompt
