format = """
\\[$username@$hostname\\] on $time \\[$directory\\]
 $character
"""
[localip]
ssh_only = true
format = '[$localipv4](bold red)'
disabled = false

[username]
style_user = "black bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold cyan)'
trim_at = "."
disabled = false

[character]
success_symbol = "[󰁕](bold white)"
error_symbol = "[󰁕](bold white)"

[time]
disabled = false
style = "green bold"
format = "[$time]($style)"

[directory]
format = "[$read_only](bold red)[$path]($style)"
read_only = "󰌾 "
truncation_length = 3
truncate_to_repo = true
style = "bold white"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = true
style = "bold italic red"
