format = """
[ $username@$hostname ](bg:#42495A)[](fg:#42495A bg:#363E4B)[$time$directory$python ](bg:#363E4B)[](fg:#363E4B)
 $character
"""
[localip]
ssh_only = true
format = '[$localipv4](bold red)'
disabled = false

[username]
style_user = "fg:#c0c0c0 bg:#42495A bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = "fg:cyan bold bg:#42495A"
trim_at = "."
disabled = false

[character]
success_symbol = "[󰁕](white)"
error_symbol = "[󰁕](white)"

[time]
disabled = true
style = "fg:green bold bg:#363E4B"
format = " [$time]($style)"

[directory]
format = " \\[[$read_only](bold red)[$path]($style)\\]"
read_only = "󰌾 "
truncation_length = 3
truncate_to_repo = true
style = "fg:bold white bg:#363E4B"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = true
style = "bold italic red"

[python]
symbol = "  "
style = "(bg:#42495A)"
format = "[${symbol}(\\($virtualenv\\))]($style)"
